version: "3.8"
services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    volumes:
      - .docker/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
  dok_site_novo:
    build: ./dok-site-novo
    volumes:
      - ./dok-site-novo/dok-site-novo:/var/www/html
    container_name: dok_site_novo
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
  dok_checkout:
    build: ./dok-checkout
    volumes:
      - ./dok-checkout/dok-checkout:/var/www/html
    container_name: dok_checkout
    env_file:
      - .env
    ports:
      - 81:80
      - 444:443
    depends_on:
      - database
  dok_painel:
    build: ./dok-painel
    volumes:
      - ./dok-painel/dok-painel:/var/www/html
    container_name: dok_painel
    env_file:
      - .env
    ports:
      - 82:80
      - 445:443
    depends_on:
      - database
  dok_consultas:
    build: ./dok-consultas
    volumes:
      - ./dok-consultas/dok-consultas:/var/www/html
    container_name: dok_consultas
    env_file:
      - .env
    ports:
      - 83:80
      - 446:443
    depends_on:
      - database
  dok_email-marketing:
    build: ./dok-email-marketing
    volumes:
      - ./dok-email-marketing/dok-email-marketing:/var/www/html
    container_name: dok_email-marketing
    env_file:
      - .env
    ports:
      - 84:80
      - 447:443
    depends_on:
      - database