version: "3.8"
networks:
  dok_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
# início banco de dados
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    volumes:
      - .docker/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      dok_network:
        ipv4_address: 172.20.0.09
# fim banco de dados

# início site
  dok_site_novo:
    build: ./dok-site-novo
    volumes:
      - ./dok-site-novo/dok-site-novo:/var/www/html
    container_name: dok_site_novo
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    networks:
      dok_network:
        aliases: 
          - dok.site
        ipv4_address: 172.20.0.10
    depends_on:
      - database
# fim site

# início checkout
  dok_checkout:
    build: ./dok-checkout
    volumes:
      - ./dok-checkout/dok-checkout:/var/www/html
    container_name: dok_checkout
    env_file:
      - .env
    ports:
      - 81:80
      - 444:443
    networks:
      dok_network:
        aliases: 
          - dok.checkout
        ipv4_address: 172.20.0.11
    depends_on:
      - database
# fim checkout

# início painel
  dok_painel:
    build: ./dok-painel
    volumes:
      - ./dok-painel/dok-painel:/var/www/html
    container_name: dok_painel
    env_file:
      - .env
    ports:
      - 82:80
      - 445:443
    networks:
      dok_network:
        aliases: 
          - dok.painel
        ipv4_address: 172.20.0.12
    depends_on:
      - database
# fim painel

# início consultas
  dok_consultas:
    build: ./dok-consultas
    volumes:
      - ./dok-consultas/dok-consultas:/var/www/html
    container_name: dok_consultas
    env_file:
      - .env
    ports:
      - 83:80
      - 446:443
    networks:
      dok_network:
        aliases: 
          - dok.consultas
        ipv4_address: 172.20.0.13
    depends_on:
      - database
# fim consultas

# início email
  dok_email-marketing:
    build: ./dok-email-marketing
    volumes:
      - ./dok-email-marketing/dok-email-marketing:/var/www/html
    container_name: dok_email-marketing
    env_file:
      - .env
    ports:
      - 84:80
      - 447:443
    networks:
      dok_network:
        aliases: 
          - dok.email
        ipv4_address: 172.20.0.14
    depends_on:
      - database
# fim email

# início seguros
  dok_seguros:
    build: ./dok-seguros
    volumes:
      - ./dok-seguros/dok-seguros:/var/www/html
    container_name: dok_seguros
    env_file:
      - .env
    ports:
      - 85:80
      - 447:443
    networks:
      dok_network:
        aliases: 
          - dok.seguros
        ipv4_address: 172.20.0.15
    depends_on:
      - database
# fim seguros